config/routes.rb
Rails.application.routes.draw do
  
  resources :businesses

  root :to => 'businesses#index'
  get '/about' => 'workers#about'
  get'/contact'=> 'workers#contact'
  get '/steps' => 'workers#steps'
  

  resources :workers do
     resources :rates
  end

  

  devise_for :admins
  

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_admin!, only: [:index, :show]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :picture)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> يحظر هذه الأعمال من يتم حفظها:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :الاسم %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :الصورة %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<div class="container">
<h2>تعديل الحرفة</h2>
<div class="well">
<%= render 'form' %>

<%= link_to 'الرجوع', businesses_path %>
</div>
</div>

app/views/businesses/index.html.erb
<div class="container">
	
<h2>قائمة الحرف</h2>
<div class="well">
<div style="text-align:center" >
 	<body>
 	<div class="row">
 	
    <% @businesses.each do |business| %>
		<h4><strong><%= business.name %></strong></h4>
		<%= image_tag(business.picture_url, :width => 150) if business.picture.present? %>
         <br>
         <br>
		<br>

        <h4><%= link_to 'اظهار', workers_path(:worker_type => business.id) %>
        	        <% if admin_signed_in?%>

        | <%= link_to 'تعديل', edit_business_path(business) %>
        | <%= link_to 'الغاء', business, method: :delete, data: { confirm: 'Are you sure?' } %>
      
      <br>
      <br>
      <%end%>
     </h4>
    <% end %>
  </div>
<br>
<br>
<% if admin_signed_in?%>
<%= link_to 'اضافة حرفة', new_business_path %>
<%end%>
 </body>
</div>
</div>
</div>

app/views/businesses/new.html.erb
<div class="container">
<h2>اضافة حرفة</h2>
<div class="well">
<%= render 'form' %>

<%= link_to 'الرجوع', businesses_path %>
</div></div>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>الاسم:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>الصورة:</strong>
<%= image_tag(@business.picture_url, :width => 150) if @business.picture.present? %>
</p>

<%= link_to 'تعديل', edit_business_path(@business) %> |
<%= link_to 'الرجوع', businesses_path %>