config/routes.rb
Rails.application.routes.draw do
  
  resources :businesses

  root :to => 'businesses#index'
  get '/about' => 'workers#about'
  get'/contact'=> 'workers#contact'
  get '/steps' => 'workers#steps'
  

  resources :workers do
     resources :rates
  end

  

  devise_for :admins
  

end

app/models/worker.rb
class Worker < ActiveRecord::Base

validates :name, presence: true
validates :telephone, presence: true
validates :region, presence: true
validates :business_id, presence: true
has_many :rates, :dependent => :destroy
belongs_to :business

accepts_nested_attributes_for :rates
validates_associated :rates


def total_average
    x = 0#rates.average('price')
    y = 0#rates.average('quality')
    z = 0#rates.average('punctuality')
    m = 0#rates.average('dealing')
    n = 0#rates.average('cleanliness')
    
    rates.each do |rate|
        x+=rate.price
        y+=rate.quality
        z+=rate.punctuality
        m+=rate.dealing
        n+=rate.cleanliness
    end
    
    
    average = ((x.to_f/rates.size+y.to_f/rates.size+z.to_f/rates.size+m.to_f/rates.size+n.to_f/rates.size)/5).round
  end
  
def average_all
  x=y=z=m=n=0
  self.rates.each do |rate|
        x+=rate.price
        y+=rate.quality
        z+=rate.punctuality
        m+=rate.dealing
        n+=rate.cleanliness
  end

  x=x.to_f/rates.size# =2# Rate.where(:worker_id => self.id).average('price').round
  y=y.to_f/rates.size
  z=z.to_f/rates.size
  m=m.to_f/rates.size
  n=n.to_f/rates.size
 
  [x.round,y.round,z.round,m.round,n.round]
  
end

def average_price
  x = Rate.where(:worker_id => self.id).average('price').round
end
def average_quality
  y =Rate.where(:worker_id => self.id).average('quality').round
end
def average_punctuality
  z = Rate.where(:worker_id => self.id).average('punctuality').round
end
def average_dealing
  m = Rate.where(:worker_id => self.id).average('dealing').round
end
def average_cleanliness
  n = Rate.where(:worker_id => self.id).average('cleanliness').round
end

end

app/controllers/workers_controller.rb
#encoding: utf-8
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_admin!, only: [:home, :index, :show ,:about , :contact,:steps]

  
def home
  
end
def about
  
end
def contact
 
end
def steps
  
end
  # GET /workers
  # GET /workers.json
  def index
    @workers=Worker.all
    @workers= @workers.where(:business_id => params[:worker_type]) if params.has_key?"worker_type"
    @workers = @workers.includes(:rates).sort_by{|x| [x.availability.to_s, x.total_average]}.reverse
    #@workers = @workers.order("availability").reverse
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
    @total_average = @worker.total_average
  end

  # GET /workers/new
  def new
    @worker = Worker.new
    @worker.rates.build
    
  end

  # GET /workers/1/edit
  def edit
  end
 

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'تم اضافة الفني بنجاح' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'تم تعديل بيانات الفني بنجاح' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'تمت ازالة الفني بنجاح ' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :telephone, :availability, :totalavg, :avcomment, :region,
      :rates_attributes => [:price, :cleanliness, :dealing, :quality, :punctuality, :comment])
    end
    
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> يحظر هذا الفني من ان يتم حفظه:</h2>
      <ul>
      	<% @worker.errors.full_messages.each do |message| %>
        	<li><%= message %></li>
     	 <% end %>
      </ul>
    </div>
  <% end %>
  <%if signed_in?%>
	<div class="row">
  		<div class="col-md-6">
  			<% if f.object.new_record? %>
   				<%= f.fields_for :rates  do |rate_fields| %>
   					<div class="field">
    					<%= rate_fields.label :السعر %><br>
    					<%= rate_fields.number_field :price, in: 1..5 %>
  					</div>
  					<div class="field">
    					<%= rate_fields.label :الجودة %><br>
    					<%= rate_fields.number_field :quality, in: 1..5 %>
  					</div>
  					<div class="field">
    					<%= rate_fields.label :الالتزام %><br>
    					<%= rate_fields.number_field :punctuality, in: 1..5 %>
  					</div>
  					<div class="field">
    					<%= rate_fields.label :النظافة %><br>
    					<%= rate_fields.number_field :cleanliness, in: 1..5 %>
  					</div>
  					<div class="field">
    					<%= rate_fields.label :التعامل %><br>
    					<%= rate_fields.number_field :dealing, in: 1..5 %>
 					</div>
 				<% end %>
 			<% end %>
  		</div>
  		<div class="col-md-6">
  			<div class="field">
  				<span style="color:black;font-weight: normal; font-size:10px; ">
    				<%= f.label :الاسم %><br>
    			</span>
    			<%= f.text_field :name %>
  			</div>
  			<div class="field">
   	 			<%= f.label :التليفون %><br>
    			<%= f.text_field :telephone %>
  			</div>
  			<div class="field">
    			<%= f.label :متاح %><br>
    			<%= f.check_box :availability %>
  			</div>
  			<div class="field">
    			<%= f.label :الحالة%><br>
    			<%= f.text_field :avcomment %>
  			</div>
  			<div class="field">
    			<%= f.label :المنطقه%><br>
    			<%= f.text_field :region %>
  			</div>
  			<div class="field">
    			<%= f.label :نوع_الحرفة%><br>
    			<%= select(:model, :attribute, Business.all.collect {|p| [ p.name, p.id ] }) %>
 			</div>
 			
 			
  		</div>
  	</div>
 
  
  <div class="actions">
    <%= f.submit %>
  </div>
  <%else%>
  <% flash[:notice]="برجاء الدخول"%>
  <%end%>
  
<% end %>

app/views/workers/_rate.html.erb
<li>
		
		<div class="row">
			<div class="col-md-6">
				<span class="rates"><%=rate %></span>
			</div>
		</div>
	<span class="timestamp">
		Posted <%= time_ago_in_words(rate.created_at)%> ago.
	</span>
	<% if current_user?(rate.user)%>
		<%= link_to "delete",post,method: :delete,data: {confirm: "You sure?"} %>
		<%= link_to "edit",edit_rate_path(rate) %>
		<%= link_to "details",rate_path(rate)%>


	<% end%>	                          
</li>

app/views/workers/about.html.erb
<div class="container">
<div class="col-md-12">

<h2>عن المشروع</h2>
<div class="well">
<p style="font-size:20px;">
	 هذا البرنامج هو احد برامج مؤسسة بناء الانسان و التنميه
	 و يهدف الى الارتقاء بمستوى الخدمه التى يحصل 
	عليها المواطن من اعمال تركيبات اوصيانه منزليه 
	لاعمال السباكه والكهرباء من خلال رفع الكفاءه و
	 تأصيل عمل الحرفيين . بدايتا بتدريب تقنى من خلال
	 مجلس التدريب الصناعى التابع لوزارة الصناعه يتبعه تدريب على القدره
	 الاداريه و مهارات التعامل مع العملاء من خلال مؤسسة البناء الانسانى و
	 التنميه ثم نقوم بتحديث هذا الموقع طبقا لاداء العامل من خلال استماره يقوم تقديمها
	  العامل للعميل عند انجاز العمل لتقييم العمل و يعيد العامل هذه الستماره للمؤسسه لتقييم جودة
	   اداء العامل على هذا الموقع لضمان استمراريه مستوى الجوده.

</p>
</div>
</div>
</div>

app/views/workers/contact.html.erb
<div class="container">
<h2>للتواصل</h2>
<div class="well">
	<h2> مؤسسة البناء الانساني و التنمية </h2>
	<h4>المشهره رقم 4011 لسنة 2011</h4><br>
	<li><h4>العنوان: </h4></li>
	<h4>عمارة (ز) الدور الخامس - شقة رقم 6- سيتي مول علي الدين - الحي السابع - مدينة 6 أكتوبر</h4><br>
	<h4>لاي استفسار يرجى الاتصال بالارقام التاليه  </h4>
	<li><h4> تليفون : </h4></li>
	<h4>01279221709</h4>
	<h4>01227334410</h4>
	<li><h4>فاكس : </h4></li>
	<h4> +2 02 39121344</h4>
	<li><h4>البريدالالكتروني :</h4></li>
	<h4>info@hfegypt.org</h4>
	<h4>thehumanfoundation@yahoo.com</h4>
</div>
</div>



 

app/views/workers/edit.html.erb
<div class="container">
<h1>تغيير بيانات </h1>
<div class="well">
<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>
</div>
</div>

app/views/workers/home.html.erb

 <div style="text-align:center" >
 	<body>
 	<div class="row">
 		<div class="col-md-2">
 			</div>
 		<div class="col-sm-4 col-offset-4">

 			<a href="www.google.com"><%= image_tag "bulb1.png", :style => "width:200px;height:300px"%></a>

 			<h3> اعمال كهرباء </h3>
		</div>
		<div class="col-md-4">
			</div>
		<div class="col-sm-4 col-offset-4">
			<%= image_tag "bristol-plumbing-one.png", :style => "width:250px;height:300px"%>

			<h3>  اعمال سباكة </h3>
		</div>
 </div>
	
</body>




</div>

app/views/workers/index.html.erb
<div class="container">
<h2>قائمة الفنيين</h2>
<% @workers.each do |worker| %>
	<% output = worker.average_all%>
	<div class="row">
	<div class="well">
		
		<div class="col-md-6 col-lg-push-6">
			<h4><strong>فني <%= worker.business.name%> &nbsp:&nbsp&nbsp&nbsp <%= worker.name %></strong></h4>
      		<h4><strong>  التليفون&nbsp&nbsp&nbsp : &nbsp&nbsp&nbsp<%= worker.telephone %></strong></h4>
      		<% if worker.availability?%>
      		
      		<h4><strong>  متاح  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:&nbsp نعم&nbsp&nbsp&nbsp,&nbsp&nbsp&nbsp&nbsp<%= worker.avcomment%></strong></h4>
      		<%else%>
      		<h4><strong>  متاح &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:&nbsp  لا &nbsp&nbsp&nbsp,&nbsp&nbsp&nbsp&nbsp<%= worker.avcomment%></strong></h4>

      		<%end%>
     		<!-- <h4><strong> المنطقه &nbsp&nbsp&nbsp&nbsp:&nbsp&nbsp <%= worker.region %></strong></h4> -->
     	 </div>
     		<div class="col-md-6 col-lg-pull-6">
     			<h4><strong>التقييم&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= show_color(worker.total_average)%></strong></h4>
     			
			</div>
		<!-- <div class="col-md-6 col-lg-pull-6">
			<h4><strong> تقييم الجوده  &nbsp&nbsp&nbsp: <%= show_stars(output[1]) %></strong></h4>
      		<h4><strong> تقييم الانضباط : <%= show_stars(output[2]) %></strong></h4>
      		<h4><strong> تقييم التعامل &nbsp&nbsp&nbsp: <%= show_stars(output[3]) %></strong></h4>
     	 	<h4><strong> تقييم النظافه &nbsp&nbsp&nbsp: <%= show_stars(output[4]) %></strong></h4>
			<h4><strong> تقييم السعر   &nbsp&nbsp&nbsp: <%= show_stars(output[0]) %></strong></h4>
		</div> -->
		<div class="row">
			<div class="col-md-12">
			<h4><%= link_to 'اظهار ', worker %>
		  | <%= link_to 'تقييم ', new_worker_rate_path(worker) %>
		<%if signed_in?%>
        	| <%= link_to 'تعديل ', edit_worker_path(worker) %>
        	| <%= link_to 'الغاء ', worker, method: :delete, data: { confirm: 'Are you sure?' } %></h4>
      	<%end%>
	</div>
	</div>

		
       
      </div>
</div>
<%end%>
</div>

app/views/workers/new.html.erb
<div class="container">
<h1> اضافة فني </h1>
<div class="well">
<%= render 'form' %>

<%= link_to 'الرجوع', workers_path %>
</div>
</div>

app/views/workers/show.html.erb
<div class="container">
<div class="well">
  <h4><strong> فني <%= @worker.business.name %>&nbsp:&nbsp&nbsp&nbsp<%= @worker.name %>   , التليفون&nbsp&nbsp&nbsp : &nbsp&nbsp&nbsp<%= @worker.telephone %></strong></h4>

 
	<% if @worker.availability?%>
      		
      		<h4><strong>  متاح&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp:&nbsp  نعم&nbsp&nbsp&nbsp,&nbsp&nbsp&nbsp&nbsp<%= @worker.avcomment%></strong></h4>
      		<%else%>
      		<strong>   متاح  :&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp لا&nbsp&nbsp&nbsp,&nbsp&nbsp&nbsp&nbsp<%= @worker.avcomment%></strong></h4>

      <%end%>
  <h4><strong>المنطقه&nbsp&nbsp&nbsp&nbsp:&nbsp&nbsp<%= @worker.region %></strong></h4>
  <h4><strong>تقييم الجوده &nbsp&nbsp&nbsp: <%= show_stars(@worker.average_quality) %></strong></h4>
  <h4><strong>تقييم الانضباط: <%= show_stars(@worker.average_punctuality) %></strong></h4>
  <h4><strong>تقييم التعامل&nbsp&nbsp&nbsp:  <%= show_stars(@worker.average_dealing) %></strong></h4>
  <h4><strong>تقييم النظافه&nbsp&nbsp&nbsp: <%= show_stars(@worker.average_cleanliness) %></strong></h4>
  <h4><strong>تقييم السعر&nbsp&nbsp&nbsp: <%= show_stars(@worker.average_price) %></strong></h4>

	<div class"row">
		<div class="col-lg-2 col-lg-push-10">
			<h4><strong>اخر ثلاث تقييمات: </strong></h4>
		</div>
	 	<div class="col-lg-10 col-lg-pull-2">
	 	<%@worker.rates.last(3).each do |rate|%>
			<div style="border-bottom: 1px gray solid; width: 25%; margin-left: 25%;"> 
			<h4>
				<strong>الجوده&nbsp&nbsp&nbsp: <%=show_stars(rate.quality)%></strong>
				<strong>الانضباط:<%=show_stars(rate.punctuality)%></strong> 
				<strong>التعامل&nbsp&nbsp&nbsp: <%=show_stars(rate.dealing)%></strong> 
				<strong>النظافه&nbsp&nbsp&nbsp:<%=show_stars(rate.cleanliness)%></strong> 
				<strong>السعر&nbsp&nbsp&nbsp: <%=show_stars(rate.price)%></strong></h4>
			</div>
		<%end%>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-2 col-lg-push-10">
  				<h4><strong>التعليقات:</strong></h4>
  		</div>
  		<div class="col-lg-10 col-lg-pull-2">
  			 <% @worker.rates.each do |rate| %>
  			 <li>
  			 	<% @worker.rates.reject(&:blank?) %>
    			<h4><strong><%= rate.comment %></strong></h4>
    		</li>
 			 <% end %>
 		</div>
  	</div>
  	<% if admin_signed_in?%>
  	<%= link_to worker_rates_path(@worker, :comments => false) do %>
  <i class="icon-ok icon-white"></i> 
  	<% if @worker.rates.any?%>
		<h4 style=color:#428bca>التقييمات: <%= @worker.rates.count%></h4>
	<%end%>
	<% end %>
	<%= link_to worker_rates_path(@worker, :comments => true) do %>
  <i class="icon-ok icon-white"></i> 
 	<h4 style=color:#428bca>التعليقات: <%= @worker.rates.where("comment IS NOT NULL").count%></h4>
<% end %>
<%end%>
<% if admin_signed_in?%>
<h4><%= link_to 'تعديل', edit_worker_path(@worker) %>
<%end%>
| <%= link_to 'رجوع', workers_path %></h4>



</div>
</div>

app/views/workers/steps.html.erb
<div class="container">
<h2>خطوات المشروع</h2>
<div class="col-md-12">
<div class="well">

<h4>  
<li>         عمل تدريب للعمال على المستوى التقنيه الحرفيه من خلال مجلس التدريب الصناعى التابع لوزارة الصناعه.
</li><br>
<li> عمل تدريب من خلال المؤسسه على القدره الاداريه و مهارات التعامل مع العملاء.
</li><br>
<li>استخراج شهاده من المؤسسه ان العامل قام بالتدريب من قبل المؤسسه على القدرات الاداريه تدرج مع الشهاده التى سيحصل عليها العامل من مجلس التدريب الصناعى (هذه شهاده للعميل و ليست شهادة ضمان للعميل فالمؤسسه ليست شركه مسئوله عن اداء العامل و لا تجنى ربح منه و لكن جهه تدريب و تقييم).
</li><br>
<li>  بعد ذلك يكون هناك تواصل مع العملاء و التاكد من التزام العامل بالعمل واخلاقيات العمل .</li><br>
<li>   يقوم العامل بابراز بطاقته الشخصيه للتأكد من ان العامل هو من قام باستقبال الاتصال من العميل و يقوم بتقديم استماره للعميل عند انجاز العمل لتقييم العمل من طرف العميل و يعيد العامل هذه الستماره للمؤسسه لتقييم جودة اداء العامل . </li><br>
<li>نقوم بعد ذلك بتحديث هذا الموقع طبقا لاداء العامل ... من هنا يشعر العامل ان اداءه يقيم و يحاول ان يحافظ على ان يكون مرشح من قبل المؤسسه فيحصل على المزيد من العمل .</li><br>
</h4>
 <%= image_tag "steps.png", :style => "width:100%"%>
</div>
</div>
</div>