config/routes.rb
Rails.application.routes.draw do
  
  resources :businesses

  root :to => 'businesses#index'
  get '/about' => 'workers#about'
  get'/contact'=> 'workers#contact'
  get '/steps' => 'workers#steps'
  

  resources :workers do
     resources :rates
  end

  

  devise_for :admins
  

end

app/models/rate.rb
class Rate < ActiveRecord::Base

  validates :price, :presence => true, length:{minimum:1 , maximum:5}
  validates :quality, :presence => true, length:{minimum:1 , maximum:5}
  validates :punctuality, :presence => true, length:{minimum:1 , maximum:5}
  validates :dealing, :presence => true, length:{minimum:1 , maximum:5}
  validates :cleanliness, :presence => true, length:{minimum:1 , maximum:5}
  validates :customer_name, :presence => true
  validates :customer_telephone, :presence => true

  belongs_to :worker
  
  
  # def total_average
    # x = Rate.average('price')
    # y = Rate.average('quality')
    # z = Rate.average('punctuality')
    # m = Rate.average('dealing')
    # n = Rate.average('cleanliness')
    # average = (x+y+z+m+n)/5
  # end
  
end

app/controllers/rates_controller.rb
#encoding: utf-8

class RatesController < ApplicationController
  before_action :set_worker
  before_action :set_rate, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_admin!, only: [:new, :create]

  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all
    @comments = params[:comments]
  end

  # GET /rates/1
  # GET /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = @worker.rates.build
  end
  
  
  # GET /rates/1/edit
  def edit
  end

  # POST /rates
  # POST /rates.json
  def create
    @rate = @worker.rates.build(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to worker_path(@worker), notice: 'تم اضافة التقييم بنجاح' }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to @rate, notice: 'تم تعديل التقييم بنجاح' }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate.destroy
    respond_to do |format|
      format.html { redirect_to worker_rates_url, notice: 'تمت ازالة التقييم' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    def set_worker
      @worker=Worker.find(params[:worker_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:quality, :price, :cleanliness, :punctuality, :dealing, :average,
       :worker_id, :review, :comment ,:customer_name, :customer_address, :customer_telephone)
    end
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/rates/_form.html.erb
<%= form_for([@worker,@rate]) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> يحظر هذا التقييم من ان يتم حفظه:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :السعر %><br>
    <%= f.number_field :price , in: 1..5%>
  </div>
  <div class="field">
    <%= f.label :الجودة %><br>
    <%= f.number_field :quality , in: 1..5%>
  </div>
  <div class="field">
    <%= f.label :الانضباط %><br>
    <%= f.number_field :punctuality , in: 1..5%>
  </div>
  <div class="field">
    <%= f.label :التعامل %><br>
    <%= f.number_field :dealing, in: 1..5 %>
  </div>

  <div class="field">
    <%= f.label :النظافة %><br>
    <%= f.number_field :cleanliness , in: 1..5%>
  </div>
 <div class="field">
 	<%= f.label :التعليق %><br>
    <%= f.text_field :comment%>
    </div>
 <div class="field">
    <%= f.label :الاسم %><br>
    <%= f.text_field :customer_name%>
  </div>
  <div class="field">
    <%= f.label :التليفون %><br>
    <%= f.text_field :customer_telephone%>
  </div>
  <div class="field">
    <%= f.label :العنوان %><br>
    <%= f.text_field :customer_address%>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/edit.html.erb
<div class="container">
	<h2>تعديل التقييم</h2>

	<div class="well">

<%= render 'form' %>

<h4><%= link_to 'اظهار', worker_rate_path(@worker.id,@rate.id) %> |
| <%= link_to 'رجوع', worker_rates_path %></h4>
</div>
</div>

app/views/rates/index.html.erb
		
<% if @comments!="true" %>
	<div class="container">
		<h2> قائمة التقييمات</h2>
		<div class="well">
			<% @worker.rates.each do |rate| %>
				<h4><strong>الجوده&nbsp&nbsp&nbsp: <%=show_stars(rate.quality)%></strong>
					<strong>الانضباط:<%=show_stars(rate.punctuality)%></strong> 
					<strong>التعامل&nbsp&nbsp&nbsp: <%=show_stars(rate.dealing)%></strong> 
					<strong>النظافه&nbsp&nbsp&nbsp:<%=show_stars(rate.cleanliness)%></strong> 
					<strong>السعر&nbsp&nbsp&nbsp: <%=show_stars(rate.price)%></strong></h4>
			
        	    <% if admin_signed_in?%>
        			<h4><%= link_to 'الغاء', worker_rate_path(@worker.id,rate.id), method: :delete, data: { confirm: 'متأكد؟' } %></h4>
       			<%end%>
			<%end%>
			<h4><%= link_to 'تقييم جديد', new_worker_rate_path %></h4>
		</div>
	</div>

<% else %>
	<div class="container">
		<h2> قائمة التعليقات</h2>
		<div class="well">
			<% @worker.rates.each do |rate| %>
					<h4><strong><%= rate.comment %></strong></h4>
					 <!-- <% if admin_signed_in?%>
        			<h4><%= link_to 'الغاء', worker_rate_path(@worker.id,rate.id), method: :delete, data: { confirm: 'متأكد؟' } %></h4>
       			<%end%> -->
			<% end %>
			<h4><%= link_to 'تقييم جديد', new_worker_rate_path %></h4>

        </div>
     </div>  
<% end %>
 	
<br>

app/views/rates/new.html.erb
<div class="container">
<h1>تقييم الفني </h1>
<div class="well">
<%= render 'form' %>

<%= link_to 'رجوع', workers_path %>
</div>
</div>

app/views/rates/show.html.erb
<div class="container">
	<h2> التقييم </h2>


<div class="well">


 <h4>
				<strong>الجوده&nbsp&nbsp&nbsp: <%=show_stars(@rate.quality)%></strong>
				<strong>الانضباط:<%=show_stars(@rate.punctuality)%></strong> 
				<strong>التعامل&nbsp&nbsp&nbsp: <%=show_stars(@rate.dealing)%></strong> 
				<strong>النظافه&nbsp&nbsp&nbsp:<%=show_stars(@rate.cleanliness)%></strong> 
				<strong>السعر&nbsp&nbsp&nbsp: <%=show_stars(@rate.price)%></strong></h4>

<div class="row">
		
	<div class="col-lg-2 col-lg-push-10">
  <h4><strong>التعليقات:</strong></h4>
  </div>
  <div class="col-lg-10 col-lg-pull-2">
  <% @worker.rates.each do |rate| %>
    <h4><strong><p><%= rate.comment %></p></strong></h4>
  <% end %>
  
 </div>
</div>
<h4><%= link_to 'تعديل', edit_worker_rate_path(@worker.id,@rate.id) %> 
| <%= link_to 'رجوع', worker_rates_path %></h4>
</div>
</div>