config/routes.rb
Rails.application.routes.draw do
  
  resources :businesses

  root :to => 'businesses#index'
  get '/about' => 'workers#about'
  get'/contact'=> 'workers#contact'
  get '/steps' => 'workers#steps'
  

  resources :workers do
     resources :rates
  end

  

  devise_for :admins
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
	
	<title>Elherafy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>



<body>


 <div role="navigation">     
	<div class="">    
		<div class="row">
			<div class="col-xs-12">
				<div style="float:left;">
				<%= image_tag "itc.png", :style => "width:150px;height:70px"%>
				
				<%= image_tag "humanfoundation.png", :style => "width:150px;height:70px"%> </div>
			
			<!-- <h1 class="title" style="background: transparent; color: black;border-width: 0px">
    			The Human Foundation  
			</h1>  -->    
			
		    <h1>
		    	الحرفى المصرى
		    </h1>
		    
		   
		 </div>
		
		</div>   
	</div> 


<div class="navbar navbar-inverse navbar-ﬁxed-top" role="navigation">     
	<div class="container">    
		<div class="navbar-header">         
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">          
				 <span class="sr-only">Toggle navigation</span>          
				 <span class="icon-bar"></span>           
				 <span class="icon-bar"></span>           
				 <span class="icon-bar"></span>         
		    </button>
		    <a class="navbar-brand" >الحرفى المصرى</a>
		 </div>
		<div class="collapse navbar-collapse bs-navbar-collapse">         
			<ul class="nav navbar-nav navbar-right"> 
				  
				 <% if signed_in? %>
					<li>
						<a href="a" class="dropdown-toggle" data-toggle="dropdown">
						
							الحساب <b class="caret " ></b>
						</a>
						<ul class="dropdown-menu">
							<li style="text-align: right;"><%= link_to "اضافة فني" , new_worker_path%></li>           
					             
							<li class="divider"></li>
							<li style="text-align: right;">
								<%= link_to "تسجيل خروج",destroy_admin_session_path , method: "delete" %>
							</li>
							
						</ul>
						</li>
					<% end %>
						<li><%= link_to "للتواصل",contact_path%>
						<li><%= link_to "خطوات المشروع",steps_path%>
						<li><%= link_to "مجلس التدريب الصناعي", "http://itcegypt.eg/"%>
						<li><%= link_to "مؤسسة بناء الانسان و التنمية", "http://www.hfegypt.org/"%></li>
						<li><%= link_to "الفنيين" , workers_path%></li>
				  		<li><%= link_to "عن المشروع" , about_path %></li>
				  		<li><%= link_to "الرئيسية" , root_path %></li>
				  		
					</ul>   
				 
				 
				
				
			</div><!--/.navbar-collapse -->     
		</div>   
	</div>


<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
 			<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
 			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

    <%= content_tag :div, msg, :class => "flash_#{name}" %>
    </div>
    
  <% end %>
  
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

	<title>Elherafy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
  </body>
</html>